// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTxo1xMz-WzCl46rjewxtu00N0TIZpfg8',
    appId: '1:856976067443:web:477ae6b340236aa84b9306',
    messagingSenderId: '856976067443',
    projectId: 'messageapp-6724b',
    authDomain: 'messageapp-6724b.firebaseapp.com',
    storageBucket: 'messageapp-6724b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVsBsEmB2CsLqy3Ahy1jgK1V9Ya8F7nO8',
    appId: '1:856976067443:android:73ba3d1d6d93af314b9306',
    messagingSenderId: '856976067443',
    projectId: 'messageapp-6724b',
    storageBucket: 'messageapp-6724b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-Rv8-3e_aX1iKKVnZU4Si7USwPquico',
    appId: '1:856976067443:ios:8dbff1c6420d522b4b9306',
    messagingSenderId: '856976067443',
    projectId: 'messageapp-6724b',
    storageBucket: 'messageapp-6724b.appspot.com',
    iosClientId: '856976067443-dq8gavt58sd5mdirsvdduk8lp775246h.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-Rv8-3e_aX1iKKVnZU4Si7USwPquico',
    appId: '1:856976067443:ios:8dbff1c6420d522b4b9306',
    messagingSenderId: '856976067443',
    projectId: 'messageapp-6724b',
    storageBucket: 'messageapp-6724b.appspot.com',
    iosClientId: '856976067443-dq8gavt58sd5mdirsvdduk8lp775246h.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );
}
